import type {
  ActivityItem,
  AlertItem,
  Entity,
  Evidence,
  InvestigationCase,
  Theory,
  TimelineEvent,
} from './types'

export const entities: Entity[] = [
  {
    id: 'ent-sarah-chen',
    type: 'person',
    label: 'Sarah Chen',
    subLabel: 'Lead Investigator',
    riskScore: 4,
    caseIds: ['CAS-2026-0148'],
    connections: 6,
    metadata: {
      Role: 'Lead Investigator',
      Team: 'Financial Crime Unit',
      Clearance: 'Tier 3',
    },
  },
  {
    id: 'ent-marcus-reed',
    type: 'person',
    label: 'Marcus Reed',
    subLabel: 'Person of Interest',
    riskScore: 88,
    caseIds: ['CAS-2026-0148'],
    connections: 9,
    metadata: {
      Status: 'Person of Interest',
      'Last Seen': 'Mar 11, 2026',
      'Linked Domains': '2',
      'Known Aliases': 'M. Reed, mreed_finance',
    },
  },
  {
    id: 'ent-elena-torres',
    type: 'person',
    label: 'Elena Torres',
    subLabel: 'Finance Coordinator — EastGate',
    riskScore: 41,
    caseIds: ['CAS-2026-0148'],
    connections: 5,
    metadata: {
      Role: 'Finance Coordinator',
      Organization: 'EastGate Logistics',
      Note: 'Account credentials compromised',
    },
  },
  {
    id: 'ent-david-holt',
    type: 'person',
    label: 'David Holt',
    subLabel: 'IT Administrator',
    riskScore: 22,
    caseIds: ['CAS-2026-0149'],
    connections: 3,
    metadata: { Role: 'IT Administrator', Organization: 'NorthStar Imports' },
  },
  {
    id: 'ent-eastgate',
    type: 'organization',
    label: 'EastGate Logistics',
    subLabel: 'Victim Organization',
    riskScore: 12,
    caseIds: ['CAS-2026-0148'],
    connections: 7,
    metadata: {
      Sector: 'Freight & Logistics',
      Headquarters: 'Rotterdam, NL',
      Employees: '420',
    },
  },
  {
    id: 'ent-horizon',
    type: 'organization',
    label: 'Horizon Financial Group',
    subLabel: 'Beneficiary Account Holder',
    riskScore: 73,
    caseIds: ['CAS-2026-0148'],
    connections: 4,
    metadata: {
      Sector: 'Financial Services',
      Note: 'Receiving account for fraudulent transfer',
    },
  },
  {
    id: 'ent-northstar',
    type: 'organization',
    label: 'NorthStar Imports',
    subLabel: 'Affiliated Vendor',
    riskScore: 35,
    caseIds: ['CAS-2026-0149'],
    connections: 3,
    metadata: { Sector: 'Import / Export' },
  },
  {
    id: 'ent-domain-legit',
    type: 'domain',
    label: 'eastgate-logistics.com',
    subLabel: 'Legitimate Domain',
    riskScore: 8,
    caseIds: ['CAS-2026-0148'],
    connections: 5,
    metadata: {
      Registrar: 'Gandi SAS',
      Created: '2014-06-02',
      Status: 'Verified',
    },
  },
  {
    id: 'ent-domain-spoof',
    type: 'domain',
    label: 'secure-eastgate-login.com',
    subLabel: 'Spoofed Phishing Domain',
    riskScore: 94,
    caseIds: ['CAS-2026-0148'],
    connections: 6,
    metadata: {
      Registrar: 'NameCheap Inc.',
      Created: '2026-03-04',
      Registrant: 'Privacy Guard (redacted)',
      Status: 'Malicious',
    },
  },
  {
    id: 'ent-domain-pay',
    type: 'domain',
    label: 'horizon-payments.net',
    subLabel: 'Payment Redirect Domain',
    riskScore: 79,
    caseIds: ['CAS-2026-0148'],
    connections: 3,
    metadata: { Registrar: 'NameCheap Inc.', Created: '2026-02-19' },
  },
  {
    id: 'ent-ip-1',
    type: 'ip',
    label: '185.233.81.14',
    subLabel: 'Hosting — Sofia, BG',
    riskScore: 86,
    caseIds: ['CAS-2026-0148'],
    connections: 5,
    metadata: {
      ASN: 'AS200000',
      Geolocation: 'Sofia, Bulgaria',
      Note: 'Hosts spoofed login portal',
    },
  },
  {
    id: 'ent-ip-2',
    type: 'ip',
    label: '91.203.17.22',
    subLabel: 'VPN Exit Node',
    riskScore: 68,
    caseIds: ['CAS-2026-0148'],
    connections: 4,
    metadata: { ASN: 'AS49981', Geolocation: 'Frankfurt, DE' },
  },
  {
    id: 'ent-ip-3',
    type: 'ip',
    label: '103.122.54.91',
    subLabel: 'Anonymizing Proxy',
    riskScore: 71,
    caseIds: ['CAS-2026-0149'],
    connections: 2,
    metadata: { ASN: 'AS133752', Geolocation: 'Hong Kong' },
  },
  {
    id: 'ent-device-1',
    type: 'device',
    label: 'Employee Laptop — ETG-4471',
    subLabel: 'Compromised Endpoint',
    riskScore: 64,
    caseIds: ['CAS-2026-0148'],
    connections: 4,
    metadata: {
      OS: 'Windows 11 Pro',
      Owner: 'Elena Torres',
      Note: 'Credential harvesting confirmed',
    },
  },
  {
    id: 'ent-device-2',
    type: 'device',
    label: 'VPN Gateway — GW-02',
    subLabel: 'Network Appliance',
    riskScore: 38,
    caseIds: ['CAS-2026-0148'],
    connections: 3,
    metadata: { Model: 'FortiGate 100F' },
  },
  {
    id: 'ent-wallet-1',
    type: 'wallet',
    label: 'bc1q9x...k4t7',
    subLabel: 'BTC Wallet',
    riskScore: 81,
    caseIds: ['CAS-2026-0148'],
    connections: 3,
    metadata: {
      Chain: 'Bitcoin',
      'Total Received': '4.82 BTC',
      'First Activity': '2026-03-09',
    },
  },
  {
    id: 'ent-email-finance',
    type: 'email',
    label: 'finance@eastgate-logistics.com',
    subLabel: 'Targeted Mailbox',
    riskScore: 30,
    caseIds: ['CAS-2026-0148'],
    connections: 5,
    metadata: { Owner: 'Elena Torres', Note: 'Recipient of phishing email' },
  },
  {
    id: 'ent-email-spoof',
    type: 'email',
    label: 'support@secure-eastgate-login.com',
    subLabel: 'Spoofed Sender',
    riskScore: 90,
    caseIds: ['CAS-2026-0148'],
    connections: 4,
    metadata: { Note: 'Sender address used in phishing campaign' },
  },
]

export const evidence: Evidence[] = [
  {
    id: 'evd-001',
    name: 'Phishing_Email_March12.eml',
    type: 'Email',
    source: 'EastGate Mail Server',
    addedAt: '2026-03-12 09:14',
    size: '48 KB',
    tags: ['phishing', 'initial-access'],
    confidence: 92,
    caseId: 'CAS-2026-0148',
    linkedEntityIds: ['ent-email-spoof', 'ent-email-finance', 'ent-domain-spoof'],
    summary:
      'Spoofed credential-reset email impersonating EastGate IT, delivered to finance@eastgate-logistics.com.',
  },
  {
    id: 'evd-002',
    name: 'VPN_Login_Records.csv',
    type: 'CSV',
    source: 'FortiGate GW-02',
    addedAt: '2026-03-12 11:02',
    size: '1.3 MB',
    tags: ['authentication', 'lateral-movement'],
    confidence: 78,
    caseId: 'CAS-2026-0148',
    linkedEntityIds: ['ent-ip-2', 'ent-device-2', 'ent-elena-torres'],
    summary:
      'VPN authentication logs showing anomalous login from Frankfurt exit node outside business hours.',
  },
  {
    id: 'evd-003',
    name: 'Invoice_Request.pdf',
    type: 'PDF',
    source: 'Finance Mailbox',
    addedAt: '2026-03-12 13:40',
    size: '210 KB',
    tags: ['fraud', 'social-engineering'],
    confidence: 85,
    caseId: 'CAS-2026-0148',
    linkedEntityIds: ['ent-horizon', 'ent-domain-pay'],
    summary:
      'Fraudulent invoice requesting urgent payment redirection to Horizon Financial Group account.',
  },
  {
    id: 'evd-004',
    name: 'Funds_Transfer_Confirmation.png',
    type: 'Image',
    source: 'Banking Portal',
    addedAt: '2026-03-12 15:55',
    size: '640 KB',
    tags: ['transaction', 'loss'],
    confidence: 88,
    caseId: 'CAS-2026-0148',
    linkedEntityIds: ['ent-horizon', 'ent-wallet-1'],
    summary:
      'Screenshot confirming a EUR 184,500 wire transfer to the beneficiary account.',
  },
  {
    id: 'evd-005',
    name: 'Endpoint_Forensics_Report.pdf',
    type: 'PDF',
    source: 'Forensics Lab',
    addedAt: '2026-03-13 08:20',
    size: '2.1 MB',
    tags: ['forensics', 'malware'],
    confidence: 74,
    caseId: 'CAS-2026-0148',
    linkedEntityIds: ['ent-device-1', 'ent-elena-torres'],
    summary:
      'Disk image analysis of ETG-4471 confirming credential-harvesting stealer artifacts.',
  },
  {
    id: 'evd-006',
    name: 'Browser_History_Report.pdf',
    type: 'PDF',
    source: 'Forensics Lab',
    addedAt: '2026-03-13 10:05',
    size: '880 KB',
    tags: ['forensics', 'phishing'],
    confidence: 69,
    caseId: 'CAS-2026-0148',
    linkedEntityIds: ['ent-device-1', 'ent-domain-spoof', 'ent-ip-1'],
    summary:
      'Browser artifacts showing the victim visited secure-eastgate-login.com prior to compromise.',
  },
  {
    id: 'evd-007',
    name: 'Chat_Export.zip',
    type: 'Archive',
    source: 'Messaging Platform',
    addedAt: '2026-03-13 16:30',
    size: '5.4 MB',
    tags: ['communication', 'coordination'],
    confidence: 57,
    caseId: 'CAS-2026-0148',
    linkedEntityIds: ['ent-marcus-reed', 'ent-horizon'],
    summary:
      'Recovered chat logs referencing payment routing and account credentials.',
  },
  {
    id: 'evd-008',
    name: 'Transaction_Records.csv',
    type: 'CSV',
    source: 'Banking Compliance',
    addedAt: '2026-03-14 09:48',
    size: '420 KB',
    tags: ['transaction', 'laundering'],
    confidence: 81,
    caseId: 'CAS-2026-0148',
    linkedEntityIds: ['ent-horizon', 'ent-wallet-1'],
    summary:
      'Outbound transaction trail showing rapid layering toward a cryptocurrency exchange.',
  },
  {
    id: 'evd-009',
    name: 'DNS_Resolution_Log.csv',
    type: 'Log',
    source: 'Network Sensor',
    addedAt: '2026-03-14 12:15',
    size: '760 KB',
    tags: ['network', 'infrastructure'],
    confidence: 63,
    caseId: 'CAS-2026-0149',
    linkedEntityIds: ['ent-ip-3', 'ent-northstar'],
    summary:
      'DNS queries resolving to anonymizing proxy infrastructure during the incident window.',
  },
]

export const cases: InvestigationCase[] = [
  {
    id: 'CAS-2026-0148',
    title: 'Business Email Compromise — EastGate Logistics',
    category: 'Business Email Compromise',
    status: 'Active',
    priority: 'High',
    lead: 'Sarah Chen',
    team: ['Sarah Chen', 'Marcus Reed', 'Elena Torres'],
    createdAt: 'March 12, 2026',
    updatedAt: '2 hours ago',
    summary:
      'A spoofed credential-reset campaign targeting EastGate Logistics finance staff led to mailbox compromise and a fraudulent EUR 184,500 wire transfer. Investigation focuses on the phishing infrastructure, compromised endpoint, and downstream laundering of funds.',
    entityIds: [
      'ent-marcus-reed',
      'ent-elena-torres',
      'ent-eastgate',
      'ent-horizon',
      'ent-domain-legit',
      'ent-domain-spoof',
      'ent-domain-pay',
      'ent-ip-1',
      'ent-ip-2',
      'ent-device-1',
      'ent-device-2',
      'ent-wallet-1',
      'ent-email-finance',
      'ent-email-spoof',
    ],
    evidenceIds: [
      'evd-001',
      'evd-002',
      'evd-003',
      'evd-004',
      'evd-005',
      'evd-006',
      'evd-007',
      'evd-008',
    ],
  },
  {
    id: 'CAS-2026-0149',
    title: 'Vendor Invoice Fraud — NorthStar Imports',
    category: 'Financial Fraud',
    status: 'Active',
    priority: 'Medium',
    lead: 'David Holt',
    team: ['David Holt', 'Sarah Chen'],
    createdAt: 'March 9, 2026',
    updatedAt: '1 day ago',
    summary:
      'Suspected vendor impersonation redirecting supplier payments through anonymizing infrastructure. Correlation analysis underway against the EastGate campaign.',
    entityIds: ['ent-david-holt', 'ent-northstar', 'ent-ip-3'],
    evidenceIds: ['evd-009'],
  },
  {
    id: 'CAS-2026-0142',
    title: 'Account Takeover Cluster — Meridian Bank',
    category: 'Account Compromise',
    status: 'Suspended',
    priority: 'Critical',
    lead: 'Elena Torres',
    team: ['Elena Torres'],
    createdAt: 'February 28, 2026',
    updatedAt: '5 days ago',
    summary:
      'Coordinated credential-stuffing activity against retail banking customers. Investigation suspended pending additional log retention from the institution.',
    entityIds: ['ent-ip-2'],
    evidenceIds: [],
  },
  {
    id: 'CAS-2026-0137',
    title: 'Insider Data Exfiltration — Cobalt Systems',
    category: 'Internal Breach',
    status: 'Closed',
    priority: 'High',
    lead: 'Marcus Reed',
    team: ['Marcus Reed', 'David Holt'],
    createdAt: 'February 14, 2026',
    updatedAt: '3 weeks ago',
    summary:
      'Departing employee exfiltrated proprietary engineering documents via personal cloud storage. Findings delivered; matter referred to legal.',
    entityIds: [],
    evidenceIds: [],
  },
]

export const timelineEvents: TimelineEvent[] = [
  {
    id: 'tl-1',
    timestamp: 'Mar 04, 2026 · 02:11 UTC',
    title: 'Phishing domain registered',
    description:
      'secure-eastgate-login.com registered through NameCheap with privacy-protected registrant details.',
    caseId: 'CAS-2026-0148',
    entityIds: ['ent-domain-spoof'],
    evidenceIds: [],
    category: 'system',
  },
  {
    id: 'tl-2',
    timestamp: 'Mar 12, 2026 · 09:14 UTC',
    title: 'Phishing email delivered',
    description:
      'Spoofed credential-reset email reaches finance@eastgate-logistics.com.',
    caseId: 'CAS-2026-0148',
    entityIds: ['ent-email-spoof', 'ent-email-finance'],
    evidenceIds: ['evd-001'],
    category: 'communication',
  },
  {
    id: 'tl-3',
    timestamp: 'Mar 12, 2026 · 09:41 UTC',
    title: 'Credentials harvested',
    description:
      'Victim submits credentials on spoofed portal hosted at 185.233.81.14.',
    caseId: 'CAS-2026-0148',
    entityIds: ['ent-ip-1', 'ent-device-1'],
    evidenceIds: ['evd-006'],
    category: 'access',
  },
  {
    id: 'tl-4',
    timestamp: 'Mar 12, 2026 · 10:58 UTC',
    title: 'Anomalous VPN login',
    description:
      'Successful VPN authentication from Frankfurt exit node 91.203.17.22 outside business hours.',
    caseId: 'CAS-2026-0148',
    entityIds: ['ent-ip-2', 'ent-device-2'],
    evidenceIds: ['evd-002'],
    category: 'access',
  },
  {
    id: 'tl-5',
    timestamp: 'Mar 12, 2026 · 13:40 UTC',
    title: 'Fraudulent invoice issued',
    description:
      'Payment-redirection invoice sent from compromised mailbox to accounts payable.',
    caseId: 'CAS-2026-0148',
    entityIds: ['ent-horizon', 'ent-domain-pay'],
    evidenceIds: ['evd-003'],
    category: 'communication',
  },
  {
    id: 'tl-6',
    timestamp: 'Mar 12, 2026 · 15:55 UTC',
    title: 'Wire transfer executed',
    description:
      'EUR 184,500 transferred to Horizon Financial Group beneficiary account.',
    caseId: 'CAS-2026-0148',
    entityIds: ['ent-horizon', 'ent-wallet-1'],
    evidenceIds: ['evd-004'],
    category: 'transaction',
  },
  {
    id: 'tl-7',
    timestamp: 'Mar 13, 2026 · 08:20 UTC',
    title: 'Correlation detected',
    description:
      'Funds layered toward cryptocurrency exchange; wallet bc1q9x...k4t7 flagged.',
    caseId: 'CAS-2026-0148',
    entityIds: ['ent-wallet-1'],
    evidenceIds: ['evd-008'],
    category: 'detection',
  },
]

export const activity: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'evidence',
    actor: 'Sarah Chen',
    action: 'uploaded evidence',
    target: 'Transaction_Records.csv',
    caseId: 'CAS-2026-0148',
    at: '2 hours ago',
  },
  {
    id: 'act-2',
    type: 'entity',
    actor: 'Sarah Chen',
    action: 'linked entity',
    target: 'Marcus Reed → secure-eastgate-login.com',
    caseId: 'CAS-2026-0148',
    at: '3 hours ago',
  },
  {
    id: 'act-3',
    type: 'timeline',
    actor: 'System',
    action: 'updated timeline',
    target: 'Correlation detected — wallet flagged',
    caseId: 'CAS-2026-0148',
    at: '5 hours ago',
  },
  {
    id: 'act-4',
    type: 'note',
    actor: 'David Holt',
    action: 'added a note',
    target: 'Proxy infrastructure overlaps with EastGate case',
    caseId: 'CAS-2026-0149',
    at: '1 day ago',
  },
  {
    id: 'act-5',
    type: 'report',
    actor: 'Marcus Reed',
    action: 'generated report',
    target: 'Insider Data Exfiltration — Final Findings',
    caseId: 'CAS-2026-0137',
    at: '3 weeks ago',
  },
]

export const alerts: AlertItem[] = [
  {
    id: 'alr-1',
    severity: 'critical',
    title: 'Funds layering detected',
    detail: 'Rapid outbound transfers toward exchange from flagged wallet.',
    caseId: 'CAS-2026-0148',
    at: '5 hours ago',
  },
  {
    id: 'alr-2',
    severity: 'high',
    title: 'Infrastructure correlation',
    detail: 'NameCheap registrant overlap across two active cases.',
    caseId: 'CAS-2026-0149',
    at: '1 day ago',
  },
  {
    id: 'alr-3',
    severity: 'medium',
    title: 'Off-hours authentication',
    detail: 'VPN login from Frankfurt exit node outside business hours.',
    caseId: 'CAS-2026-0148',
    at: '2 days ago',
  },
]

export const theories: Theory[] = [
  {
    id: 'thy-1',
    title: 'Compromised employee account used for intrusion',
    caseId: 'CAS-2026-0148',
    confidence: 82,
    supporting: [
      'Credential-harvesting artifacts on ETG-4471',
      'Browser history shows visit to spoofed portal',
      'VPN login from anomalous geolocation',
    ],
    contradicting: ['No malware persistence mechanism recovered'],
  },
  {
    id: 'thy-2',
    title: 'Horizon account is a money mule network node',
    caseId: 'CAS-2026-0148',
    confidence: 64,
    supporting: [
      'Rapid layering toward cryptocurrency exchange',
      'Account created two weeks before incident',
    ],
    contradicting: ['Beneficiary identity not yet verified'],
  },
]

export const stats = {
  totalCases: 4,
  activeInvestigations: 2,
  closedCases: 1,
  highPriority: 3,
}

export function getCase(id: string) {
  return cases.find((c) => c.id === id)
}

export function getEntity(id: string) {
  return entities.find((e) => e.id === id)
}

export function getEvidence(id: string) {
  return evidence.find((e) => e.id === id)
}
